### ISSUE TITLE
Code Requests for paper

### ISSUE THREAD

**Issue by kanseaveg** [DaoD/INTERS#1]
Hello author, your work is written very well. I am very interested in your work. May I ask when the source code will be open? I can't wait to study it.

**Comment by DaoD** [comment]
Thanks so much! We plan to release all resouces within a month. We would like to send you a notification when everything is ready.

**Comment by kanseaveg** [comment]
Okay, thank you for the answer. I am looking forward to it.

**Comment by DaoD** [comment]
@kanseaveg The fine-tuned model and dataset have been released.
