### ISSUE TITLE
数据集还有模型啥时候开放呢

### ISSUE THREAD

**Issue by zhangatao** [DaoD/INTERS#2]
很棒的工作，主页的模型还有数据链接，现在都不能访问，请问这个大概啥时候会开放呢

**Comment by DaoD** [comment]
您好，谢谢您的关注以及对我们工作的肯定。代码、数据和模型预计将在一个月内放出。准备完成后我们可以给您发送通知。

**Comment by DaoD** [comment]
@zhangatao 数据集和模型已发布
